### ISSUE TITLE
Concurrency issue?

### ISSUE THREAD

**Issue by shyamchin** [aliakh/demo-akka-spring#1]
Hi,
I cloned your code base and just only slightly modified Message.java to alter the field names ('id' changed to 'numInvokes')

Then I took up a small load test of 15 requests by two concurrent users  using Gatling tool. I got the following exception (1 failure out of 15). 

Repeated runs show around 2-3 such failures for each 15 requests load run.  However, the numInvokes counter seems to be getting incremented correctly even with these exceptions occurring. 

Thanks

10/05 09:41:56.927 INFO [main] o.s.b.a.e.m.EndpointHandlerMapping - Mapped "{[/configprops || /configprops.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
10/05 09:41:56.931 INFO [main] o.s.b.a.e.m.EndpointHandlerMapping - Mapped "{[/beans || /beans.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
10/05 09:41:57.242 INFO [main] o.a.c.h.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
10/05 09:41:57.267 INFO [main] o.a.c.h.Http11NioProtocol - Starting ProtocolHandler [http-nio-8080]
10/05 09:41:57.280 INFO [main] o.a.t.u.n.NioSelectorPool - Using a shared selector for servlet write/read
10/05 09:41:57.358 INFO [main] o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat started on port(s): 8080 (http)
10/05 09:41:57.389 INFO [main] d.Application - Started Application in 7.549 seconds (JVM running for 8.128)
10/05 09:42:17.891 INFO [http-nio-8080-exec-1] o.a.c.c.C.[.[.[/] - Initializing Spring FrameworkServlet 'dispatcherServlet'
10/05 09:42:17.891 INFO [http-nio-8080-exec-1] o.s.w.s.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization started
10/05 09:42:17.919 INFO [http-nio-8080-exec-1] o.s.w.s.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization completed in 28 ms
10/05 09:42:18.077 INFO [demo-actor-system-akka.actor.default-dispatcher-4] d.s.BusinessService - Perform: demo.actor.WorkerActor@45740407 Message{payload='async-non-blocking', numInvokes=0}
10/05 09:50:07.560 INFO [demo-actor-system-akka.actor.default-dispatcher-5] d.s.BusinessService - Perform: demo.actor.WorkerActor@a1e94c8 Message{payload='async-non-blocking', numInvokes=1}
10/05 09:50:07.622 ERROR[http-nio-8080-exec-4] o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is akka.actor.InvalidActorNameException: actor name [worker-actor] is not unique!] with root cause
akka.actor.InvalidActorNameException: actor name [worker-actor] is not unique!
        at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:129)
        at akka.actor.dungeon.Children$class.reserveChild(Children.scala:130)
        at akka.actor.ActorCell.reserveChild(ActorCell.scala:374)
        at akka.actor.dungeon.Children$class.makeChild(Children.scala:268)
        at akka.actor.dungeon.Children$class.attachChild(Children.scala:46)
        at akka.actor.ActorCell.attachChild(ActorCell.scala:374)
        at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:571)
        at demo.service.CompletableFutureService.get(CompletableFutureService.java:23)
        at demo.controller.DeferredResultController.getAsyncNonBlocking(DeferredResultController.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:107)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
10/05 09:50:08.266 INFO [demo-actor-system-akka.actor.default-dispatcher-6] d.s.BusinessService - Perform: demo.actor.WorkerActor@6335ae3b Message{payload='async-non-blocking', numInvokes=3}
10/05 09:50:08.424 INFO [demo-actor-system-akka.actor.default-dispatcher-5] d.s.BusinessService - Perform: demo.actor.WorkerActor@e6ffb8 Message{payload='async-non-blocking', numInvokes=4}
10/05 09:50:09.282 INFO [demo-actor-system-akka.actor.default-dispatcher-5] d.s.BusinessService - Perform: demo.actor.WorkerActor@3ba21560 Message{payload='async-non-blocking', numInvokes=5}
10/05 09:50:09.402 INFO [demo-actor-system-akka.actor.default-dispatcher-6] d.s.BusinessService - Perform: demo.actor.WorkerActor@69cdc54b Message{payload='async-non-blocking', numInvokes=6}
10/05 09:50:10.316 INFO [demo-actor-system-akka.actor.default-dispatcher-5] d.s.BusinessService - Perform: demo.actor.WorkerActor@746b275c Message{payload='async-non-blocking', numInvokes=7}
10/05 09:50:10.336 INFO [demo-actor-system-akka.actor.default-dispatcher-6] d.s.BusinessService - Perform: demo.actor.WorkerActor@2ccf5616 Message{payload='async-non-blocking', numInvokes=8}
10/05 09:50:11.265 INFO [demo-actor-system-akka.actor.default-dispatcher-7] d.s.BusinessService - Perform: demo.actor.WorkerActor@5a9844ff Message{payload='async-non-blocking', numInvokes=9}
10/05 09:50:11.274 INFO [demo-actor-system-akka.actor.default-dispatcher-6] d.s.BusinessService - Perform: demo.actor.WorkerActor@624571c2 Message{payload='async-non-blocking', numInvokes=10}
10/05 09:50:12.270 INFO [demo-actor-system-akka.actor.default-dispatcher-7] d.s.BusinessService - Perform: demo.actor.WorkerActor@545fb1dc Message{payload='async-non-blocking', numInvokes=11}
10/05 09:50:13.265 INFO [demo-actor-system-akka.actor.default-dispatcher-5] d.s.BusinessService - Perform: demo.actor.WorkerActor@43c70d56 Message{payload='async-non-blocking', numInvokes=12}
10/05 09:50:14.289 INFO [demo-actor-system-akka.actor.default-dispatcher-7] d.s.BusinessService - Perform: demo.actor.WorkerActor@50602f8f Message{payload='async-non-blocking', numInvokes=13}
10/05 09:50:15.290 INFO [demo-actor-system-akka.actor.default-dispatcher-5] d.s.BusinessService - Perform: demo.actor.WorkerActor@25cb9e8f Message{payload='async-non-blocking', numInvokes=14}
10/05 09:50:16.263 INFO [demo-actor-system-akka.actor.default-dispatcher-7] d.s.BusinessService - Perform: demo.actor.WorkerActor@1562bbe7 Message{payload='async-non-blocking', numInvokes=15}

**Comment by shyamchin** [comment]
I added a unique id key to the actor name by modifying the line in CompletableFutureService.java

```
    ActorRef workerActor = actorSystem.actorOf(springExtension.props("workerActor", future), "worker-actor-" + UUID.randomUUID());
```

That seems to have fixed it. 
Thanks for the great starter project!
